services:
    web:
        build: .
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=db
        depends_on:
            - db    
    db:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=db
volumes:
    pg_data: