services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/stock
        ports:
            - 8000:8000
        environment:
            - CELERY_BROKER=redis://redis:6379
            - CELERY_RESULT_BACKEND=redis://redis:6379
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=db
        depends_on:
            - db
            - celery_worker
            - redis
    db:
        image: postgres:latest
        restart: always
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=db
    redis:
        container_name: redis_container
        image: redis:latest
        restart: always

    celery_worker:
        build: .
        command: celery -A backend.celery worker --pool=solo -l info
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis

volumes:
    pg_data: