# fly.toml file generated for kk-stock on 2022-11-21T16:05:47+08:00

app = "kk-stock"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
web = "gunicorn --bind :8000 --workers 2 backend.wsgi"
worker = "celery -A backend.celery worker --pool=solo -l info"

[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"